package com.byjusexamprep.newapp.models

data class Product(
    val brand_ids: String,
    val brand_name: String,
    val button_text: String,
    val catalog_tag: List<String>,
    val category_ids: String,
    val discount: Int,
    val dynamic_tags: List<Any>,
    val expdt: Any,
    val explore_more: Any,
    val fbn: Int,
    val final_price: Int,
    val from_gludo: Int,
    val gludo_stock: Boolean,
    val id: String,
    val image_url: String,
    val is_backorder: Int,
    val is_kit_combo: Any,
    val is_lux: Int,
    val is_saleable: Boolean,
    val mrp_freeze: Any,
    val name: String,
    val object_type: String,
    val offers: Any,
    val pack_size: Any,
    val price: Int,
    val primary_categories: PrimaryCategories,
    val pro_flag: Int,
    val quantity: Int,
    val rating: Double,
    val rating_count: Int,
    val show_wishlist_button: Int,
    val sku: String,
    val slug: String,
    val type: String,
    var noMoreDataItem : Boolean = false
)