package com.byjusexamprep.newapp.models

data class Response(
    val android_landing_url: Any,
    val app_sorting: String,
    val art_content: Any,
    val art_link_text: Any,
    val art_pos: Any,
    val art_title: Any,
    val art_url: Any,
    val auth_certificate: Any,
    val banner_image: Any,
    val banner_video: Any,
    val banner_video_image: Any,
    val category_name: String,
    val child_categories: Any,
    val desktop_tip_tile: Any,
    val filter_keys: FilterKeys,
    val filters: Filters,
    val font_color: Any,
    val ios_landing_url: Any,
    val isNewApi: Boolean,
    val level: Int,
    val namespace: List<String>,
    val offset: Int,
    val other_filters: OtherFilters,
    val product_count: Int,
    val products: MutableList<Product>,
    val query: String,
    val size_chart_image: Any,
    val sort: String,
    val stop_further_call: Int,
    val tip_tile: Any,
    val title: String,
    val total_found: Int,
    val type: String,
    val url: String
)